title: <p align="center"> Prashant Vhatkar </p>
logo: /assets/img/profile.enc

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vhatkarprash/">LinkedIn</a> |
  <a href="https://github.com/HAJ1MEI">GitHub</a>
 
  <br>  
  Full Stack developer specialized in Java Springboot.
  Project-Focused Portfolio featuring real-world applications
  like an e-commerce platform, event management system, and a metaverse library built in Unreal Engine.
  <br>
  </p>



theme: jekyll-theme-minimal
